export const booksGenres = [
  { value: "fiction", label: "Ficción" },
  { value: "mystery", label: "Misterio" },
  { value: "romance", label: "Romance" },
  { value: "sci-fi", label: "Ciencia Ficción" },
  { value: "fantasy", label: "Fantasía" },
  { value: "adventure", label: "Aventura" },
  { value: "horror", label: "Terror" },
  { value: "non-fiction", label: "No Ficción" },
  { value: "biography", label: "Biografía" },
  { value: "history", label: "Historia" },
  { value: "science", label: "Ciencia" },
  { value: "technology", label: "Tecnología" },
  { value: "self-help", label: "Autoayuda" },
  { value: "business", label: "Negocios" },
  { value: "art", label: "Arte" },
  { value: "music", label: "Música" },
  { value: "cooking", label: "Cocina" },
  { value: "travel", label: "Viajes" },
  { value: "religion", label: "Religión" },
];
